### PR TITLE
Make log path configurable

### PR DESCRIPTION
**Pull request by benrs**
Not directly linked to an issue, but thought this could be useful.

### CODE REVIEW

**Comment by robertoaloi** [comment]
Hi @benrs and thanks for the contribution. As part of https://github.com/erlang-ls/erlang_ls/issues/430 we plan to refactor the command line options for the language server, so I suggest we keep this one on hold until we define the final format for the options. What do you think?

**Comment by benrs** [comment]
Sounds good to me, I'll follow the conversation in the issue you linked and see what I can do to help.

**Comment by benrs** [comment]
Should we revisit merging this now? I have another branch lined up to support the `--log-level` option when [this](https://github.com/erlang-ls/erlang_ls/pull/475) is merged.

**Comment by jfacorro** [comment]
@benrs I didn't notice this PR (and the discussion in it) before merging this other one #35 which implements the `--log-level` configuration option.

**Comment by benrs** [comment]
@jfacorro All good!

**Pull request merged**
