### PR TITLE
WIP: Initial attempt

### PR DESCRIPTION
**Pull request by adam-becker**
This PR is not tested, but should be enough to start a conversation.

### CODE REVIEW

**Comment by adam-becker** [comment]
@robertoaloi This is probably over-simplified, and I think a `.vscodeignore` file is still required to get rid of unwanted artifacts from the package.

**Comment by robertoaloi** [comment]
The `erlang-ls` organization and account is now created.

**Comment by robertoaloi** [comment]
And the extension is now (manually) published to the marketplace:

https://marketplace.visualstudio.com/items?itemName=erlang-ls.erlang-ls

**Comment by adam-becker** [comment]
@robertoaloi What steps did you have to go through to publish?

**Comment by alanz** [comment]
FYI we have auto-deploy on `vscode-hie-server`, via a travis job.  See https://github.com/alanz/vscode-hie-server/blob/master/.travis.yml#L45-L62

It deploys if a tag is added on master and the tests pass.

**Comment by robertoaloi** [comment]
@adam-becker I followed the instructions in your link. Essentially, after creating the `erlang-ls` organization:

```
npm install
vsce package
vsce publish
```

I had to add the publisher (`erlang-ls`) in the `package.json` and fix the name to ensure it didn't include underscores (I think we should actually get rid of the `erlang_ls` version of the name to avoid the inconsistency between hyphen and underscore.

In the future, I suggest we automatically publish the escript in the `erlang_ls` repo on merges to master and/or new tags and use that  in this extension.

**Comment by adam-becker** [comment]
@robertoaloi In that case, I think the easier thing to do would be to just have the extension always download the latest release when it's installed.

**Comment by robertoaloi** [comment]
@adam-becker That approach (download latest on install) has a big drawback: it could make it hard for us to identify bugs. We will end up with users reporting bugs for a given extension tag, but we will not know what version of the language server they are using. I would prefer the extension to always use a pinned version of the server.

**Comment by alanz** [comment]
See also https://github.com/erlang-ls/vscode/pull/13 and https://github.com/erlang-ls/erlang_ls/pull/279 which together give more control as well as visibility into the server version being used.

**Comment by adam-becker** [comment]
@robertoaloi We could add a command (Accessible from VSCode's command palette) that displays the version number on demand, as a complement to what @alanz has done.

**Comment by robertoaloi** [comment]
@alanz @adam-becker What do we want to do with this? We need some CI, but I'm not sure we should rely on the alpha version of the vscode action. Maybe we should check if there's a more solid one or we could even write our own?

**Comment by adam-becker** [comment]
I'm a big believer in keeping CI scripts separate from whatever tool is being used to run the CI. So a first step would be to codify the process of creating a release of this extension, passing any secrets as inputs.

I'm personally most experienced with GitLab CI, but any of these tools should be capable of executing `./build` in a pre-defined docker image.

**Pull request closed without merging**
